# Generated by Django 4.0.4 on 2022-05-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=200)),
                ('measure_type', models.CharField(max_length=20)),
                ('producer_name', models.CharField(max_length=200)),
            ],
        ),
    ]
