# Generated by Django 4.0.4 on 2022-05-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='income_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
