# Generated by Django 4.0.4 on 2022-05-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_good_income_date_good_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='income_date',
            field=models.DateTimeField(),
        ),
    ]
