# Generated by Django 4.0.4 on 2022-05-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_good_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='income_date',
            field=models.DateField(),
        ),
    ]
