# Generated by Django 4.0.4 on 2022-05-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_good_income_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Good',
            new_name='Goods',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='good_name',
            new_name='goods_name',
        ),
    ]
